#!/bin/bash

USAGE="""
Usage: ./create_docker_image -c CUSTOMER -v VERSION
    -c --customer
        The customer you release version for.
    -v --version
        The tag version you release.
"""

PATH_TO_COOG_ADMIN='/home/coog/workspace/coog-admin/'

_generate() {
    $PATH_TO_COOG_ADMIN/build coog/$1:$2 \
        customers:$1-coog-$2 \
        coog:coog-$2 \
        trytond:coog-$2 \
        trytond-modules:coog-$2 \
        coog-bench:coog-$2 \
        sao:coog-$2
}

main(){
 _generate $CUSTOMER $VERSION
}

# Script begins here
[ $# -lt 2 ] && echo "$USAGE" && exit 1

while [[ $# -gt 1 ]]; do

    arg="$1"
    value="$2"
    case $arg in
        -c|--customer)
            CUSTOMER="$value"
            shift
            ;;
        -v|--version)
            VERSION="$value"
            shift
            ;;
        *)
            echo "Invalid argument $arg."
            return 1
            ;;
    esac
    shift
done

[ -z "$CUSTOMER" ] && echo "Missing required parameter.$USAGE" && exit 1
[ -z "$VERSION" ] && echo "Missing required parameter.$USAGE" && exit 1

main "$@"
