#!/bin/bash

USAGE="""
Usage: ./report -v VERSION -o OLD_VERSION [ OPTIONS ]
    -v --version
        The tag version you release.
    -o --old-version
        The old released version you want to see diff.
    -p --path
        The path in which to search for git tag. Default is $PWD.
    -a --admin
        The path to coog-admin Default is $PWD/../coog-admin.
"""

IFS=$'\n'

customers_in_version=()

calculate_customer_version(){
    major_version=`cut -d '.' -f 1,2 <<< $VERSION`

    for customer in $(cat ./customers); do
        customer_version=`cut -d ':' -f 2 <<< $customer`
        if [[ $customer_version == *"$major_version"* ]]; then
            name=`cut -d ':' -f 1 <<< $customer`
            customers_in_version+=($name)
        fi
    done
}

_fetch_origin() {
    git fetch
}

_list_common_issues() {
    git \
        -C "$1" \
        rev-list --format=%B \
        "coog-$VERSION" \
        ^"coog-$OLD_VERSION" | \
        grep -E "Fix #" | \
        sed -e "s/.*Fix *# *\([0-9]\+\).*/\1/"
}

_list_customer_issues() {
    git \
        -C "$1" \
        rev-list --format=%B \
        "$2-coog-$VERSION" \
        ^"$2-coog-$OLD_VERSION" | \
        grep -E "Fix #" | \
        sed -e "s/.*Fix *# *\([0-9]\+\).*/\1/"
}

_list_all_issues() {
    for repo in $(cat ./repos.common); do
        _fetch_origin
        if [ "$repo" == "customers" ]; then
            for customer in ${customers_in_version[@]}; do
                echo "[$customer]" >> issues
                _list_customer_issues $"$WORKING_PATH/$repo" "$customer" >> issues 2>/dev/null
            done
        else
            echo "[$repo]" >> issues
            _list_common_issues $"$WORKING_PATH/$repo" >> issues 2>/dev/null            
        fi
    done
}

_docker_images(){
    # generate coog vanilla image
    ./create_docker_image -c coog -v "$VERSION" -a "$COOG_ADMIN_PATH" -i "coog"
    # generate customer coog image
    for customer in ${customers_in_version[@]}; do
        ./build_coog_customers.sh -v "$VERSION" -c "$customer"
    done
    # create coog web vanilla image
    ./create_docker_image -c coog -v "$VERSION" -a "$COOG_ADMIN_PATH" -i "web"
    # create customer web image (don't forget to fill the web_customers file in ./web_image_build)
    ./web_image_build/build_image_web "$VERSION" 
    # create unoconv image
    ./create_docker_image -c coog -v "$VERSION" -a "$COOG_ADMIN_PATH" -i "unoconv"
}

_checkout_coog_admin(){
    major_version=`cut -d '.' -f 1,2 <<< $VERSION`

    git \
        --git-dir=$COOG_ADMIN_PATH/.git \
        --work-tree=$COOG_ADMIN_PATH/ \
        checkout "coog-$major_version"
}

_remove_bench_tmp_files(){
    # this is required because in 2.0 it's using a coog user in the bench 
    # build docker file.
    if [ -d "/tmp/coog-bench" ]; then
        sudo rm -rf /tmp/coog-bench
    fi
}

main() {
    _checkout_coog_admin
    calculate_customer_version
    _list_all_issues
    python issues_converter.py
    python create_versions.py $VERSION
    python bl_support.py $VERSION
    python html_to_pdf.py
    _remove_bench_tmp_files
    _docker_images
}

# Script begins here
[ $# -lt 3 ] && echo "$USAGE" && exit 1

while [[ $# -gt 1 ]]; do

    arg="$1"
    value="$2"
    case $arg in
        -p|--path)
            WORKING_PATH="$value"
            shift
            ;;
        -v|--version)
            VERSION="$value"
            shift
            ;;
        -o|--old-version)
            OLD_VERSION="$value"
            shift
            ;;
        -a|--admin)
            COOG_ADMIN_PATH="$value"
            shift
            ;;
        *)
            echo "Invalid argument $arg."
            return 1
            ;;
    esac
    shift
done

[ -z "$VERSION" ] && echo "Missing required parameter.$USAGE" && exit 1
[ -z "$OLD_VERSION" ] && echo "Missing required parameter.$USAGE" && exit 1
[ -z "$WORKING_PATH" ] && WORKING_PATH="$PWD"
[ -z "$COOG_ADMIN_PATH" ] && COOG_ADMIN_PATH=`readlink -f $PWD/../coog-admin`

main "$@"
